### ISSUE TITLE
Severe Performance Loss when Rendering NPC's

### ISSUE THREAD

**Issue by NickelSilver** [NickelSilver/Project-Cold-Iota#2]
PyOpenGL isn't exactly the fastest pony at the racetrack. Instant rendering of polygons (e.g. GL_QUADS), even small ones, slows down system considerably. As such, NPC objects need to be converted to Vertex Buffer Objects (VBO's). I will implement this as soon as I can wrap my head around it.

**Comment by dre576** [comment]
please send me the slides

**Comment by NickelSilver** [comment]
VBO's turned out to be less beneficial than expected. However, I managed to create a successful workaround by adjusting the frames each movement takes and the distance covered per frame based off of the number of NPC's.
